# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Dozzle Agent
version: "1.0.3"
slug: dozzle-agent
description: Dozzle can run in agent mode which can expose Docker hosts to other Dozzle instances. All communication is done over a secured connection using TLS. This means that you can deploy Dozzle on a remote host and connect to it from your local machine.
url: "https://github.com/zeillemaker/homeassistant-dozzle-agent/tree/main/dozzle-agent"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  7007/tcp: 7007
apparmor: false
host_dbus: true
docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
#image: "ghcr.io/jkpe/{arch}-addon-dozzle-agent"
